server:
  port: 8070

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: store-service
          uri: lb://user-service
          predicates:
            - Path=/stores/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**